# Generated by Django 6.0.6 on 2026-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unverified_user_ttl_days', models.PositiveIntegerField(default=14)),
                ('post_ttl_days', models.PositiveIntegerField(default=90)),
            ],
        ),
    ]
